// Codes we have no logo file for in public/airlines/ (the source CDN,
// pics.avs.io, had no image for them as of 2026-08-12) — return null so
// callers skip the image instead of requesting a known 404. N9 is
// different: the CDN *has* an image, but for a defunct code-holder (Kabo
// Air), not the Shree Airlines we list — better no logo than the wrong one.
const NO_CDN_LOGO_CODES = new Set([
  "N9",
  "0D", "0P", "11", "12", "13", "1F", "1K", "1T", "1X", "24", "2F", "2N",
  "2O", "2X", "3G", "3Q", "47", "4A", "4D", "4P", "5M", "69", "6D", "6F",
  "6G", "6P", "6T", "6V", "76", "77", "78", "7O", "88", "8A", "8K", "8O",
  "99", "9L", "9T", "9Y", "AX", "B1", "BN", "BQ", "C0", "C1", "C5", "C9",
  "CB", "CF", "CH", "CW", "D1", "D6", "DA", "DF", "DK", "DO", "E1", "E3",
  "EA", "EF", "EJ", "EM", "F1", "F5", "FF", "FK", "G0", "G1", "GB", "GG",
  "GN", "GO", "GT", "HP", "HT", "I7", "IC", "IP", "IV", "JK", "JZ", "K5",
  "KG", "KH", "KJ", "KW", "L1", "L3", "L5", "L7", "L8", "M1", "M2", "M4",
  "M7", "MA", "N1", "N5", "NB", "NJ", "NM", "NW", "O1", "O2", "OF", "OH",
  "OP", "P7", "P8", "PH", "PP", "PT", "Q7", "QA", "QO", "QT", "QX", "QY",
  "R4", "R7", "RD", "RH", "RN", "RP", "S1", "S3", "S5", "S9", "SO", "T2",
  "T4", "TE", "TH", "U1", "U3", "UF", "UZ", "V1", "V2", "V8", "V9", "VC",
  "VD", "VI", "W1", "W7", "WC", "WD", "WH", "WQ", "XA", "XB", "XV", "YD",
  "YH", "YR", "YX", "YZ", "Z3", "Z4", "Z5", "ZC", "ZJ", "ZN", "ZS", "ZY",
]);

// Real airline logos by 2-letter IATA code, self-hosted in public/airlines/
// (downloaded once from Aviasales' CDN, which has correct logos for reused
// codes like U4/Buddha Air) so they load same-origin with no external CDN
// or image-optimizer round-trip. Returns null when no code is given so
// callers can skip rendering an image rather than showing a broken one.
export function airlineLogoUrl(code?: string | null): string | null {
  const trimmed = code?.trim().toUpperCase();
  if (!trimmed || trimmed.length !== 2) return null;
  if (NO_CDN_LOGO_CODES.has(trimmed)) return null;

  return `/airlines/${trimmed}.png`;
}

export interface Airline {
  name: string;
  code: string;
  country?: string;
}

// Worldwide scheduled carriers by IATA code: a hand-ranked block of major
// airlines first (so a short prefix surfaces the big names), followed by the
// full set of active IATA-coded airlines from the OpenFlights open dataset —
// local and international carriers for every country. Kept client-side
// (~30 KB) so the dropdown is instant from the very first keystroke, same as
// the destination field.
const AIRLINES: Airline[] = [
  { name: "Qatar Airways", code: "QR", country: "Qatar" },
  { name: "Emirates", code: "EK", country: "United Arab Emirates" },
  { name: "Singapore Airlines", code: "SQ", country: "Singapore" },
  { name: "Turkish Airlines", code: "TK", country: "Turkey" },
  { name: "Lufthansa", code: "LH", country: "Germany" },
  { name: "British Airways", code: "BA", country: "United Kingdom" },
  { name: "Air France", code: "AF", country: "France" },
  { name: "KLM Royal Dutch Airlines", code: "KL", country: "Netherlands" },
  { name: "Etihad Airways", code: "EY", country: "United Arab Emirates" },
  { name: "Cathay Pacific", code: "CX", country: "Hong Kong" },
  { name: "Japan Airlines", code: "JL", country: "Japan" },
  { name: "All Nippon Airways", code: "NH", country: "Japan" },
  { name: "Korean Air", code: "KE", country: "South Korea" },
  { name: "Thai Airways International", code: "TG", country: "Thailand" },
  { name: "Malaysia Airlines", code: "MH", country: "Malaysia" },
  { name: "Cathay Dragon", code: "KA", country: "Hong Kong" },
  { name: "Air India", code: "AI", country: "India" },
  { name: "IndiGo", code: "6E", country: "India" },
  { name: "Vistara", code: "UK", country: "India" },
  { name: "SpiceJet", code: "SG", country: "India" },
  { name: "Nepal Airlines", code: "RA", country: "Nepal" },
  { name: "Buddha Air", code: "U4", country: "Nepal" },
  { name: "Yeti Airlines", code: "YT", country: "Nepal" },
  { name: "Himalaya Airlines", code: "H9", country: "Nepal" },
  { name: "American Airlines", code: "AA", country: "United States" },
  { name: "Delta Air Lines", code: "DL", country: "United States" },
  { name: "United Airlines", code: "UA", country: "United States" },
  { name: "Southwest Airlines", code: "WN", country: "United States" },
  { name: "Alaska Airlines", code: "AS", country: "United States" },
  { name: "JetBlue Airways", code: "B6", country: "United States" },
  { name: "Spirit Airlines", code: "NK", country: "United States" },
  { name: "Frontier Airlines", code: "F9", country: "United States" },
  { name: "Air Canada", code: "AC", country: "Canada" },
  { name: "WestJet", code: "WS", country: "Canada" },
  { name: "Aeromexico", code: "AM", country: "Mexico" },
  { name: "Copa Airlines", code: "CM", country: "Panama" },
  { name: "LATAM Airlines", code: "LA", country: "Chile" },
  { name: "Avianca", code: "AV", country: "Colombia" },
  { name: "Gol Linhas Aereas", code: "G3", country: "Brazil" },
  { name: "Azul Brazilian Airlines", code: "AD", country: "Brazil" },
  { name: "Aerolineas Argentinas", code: "AR", country: "Argentina" },
  { name: "Iberia", code: "IB", country: "Spain" },
  { name: "Vueling", code: "VY", country: "Spain" },
  { name: "Ryanair", code: "FR", country: "Ireland" },
  { name: "easyJet", code: "U2", country: "United Kingdom" },
  { name: "Wizz Air", code: "W6", country: "Hungary" },
  { name: "TAP Air Portugal", code: "TP", country: "Portugal" },
  { name: "ITA Airways", code: "AZ", country: "Italy" },
  { name: "Swiss International Air Lines", code: "LX", country: "Switzerland" },
  { name: "Austrian Airlines", code: "OS", country: "Austria" },
  { name: "Brussels Airlines", code: "SN", country: "Belgium" },
  { name: "Scandinavian Airlines", code: "SK", country: "Sweden" },
  { name: "Finnair", code: "AY", country: "Finland" },
  { name: "Norwegian Air Shuttle", code: "DY", country: "Norway" },
  { name: "Icelandair", code: "FI", country: "Iceland" },
  { name: "Aer Lingus", code: "EI", country: "Ireland" },
  { name: "LOT Polish Airlines", code: "LO", country: "Poland" },
  { name: "Czech Airlines", code: "OK", country: "Czech Republic" },
  { name: "Aegean Airlines", code: "A3", country: "Greece" },
  { name: "Air Serbia", code: "JU", country: "Serbia" },
  { name: "Croatia Airlines", code: "OU", country: "Croatia" },
  { name: "Pegasus Airlines", code: "PC", country: "Turkey" },
  { name: "Aeroflot", code: "SU", country: "Russia" },
  { name: "Air China", code: "CA", country: "China" },
  { name: "China Southern Airlines", code: "CZ", country: "China" },
  { name: "China Eastern Airlines", code: "MU", country: "China" },
  { name: "Hainan Airlines", code: "HU", country: "China" },
  { name: "EVA Air", code: "BR", country: "Taiwan" },
  { name: "China Airlines", code: "CI", country: "Taiwan" },
  { name: "Asiana Airlines", code: "OZ", country: "South Korea" },
  { name: "Vietnam Airlines", code: "VN", country: "Vietnam" },
  { name: "VietJet Air", code: "VJ", country: "Vietnam" },
  { name: "Philippine Airlines", code: "PR", country: "Philippines" },
  { name: "Cebu Pacific", code: "5J", country: "Philippines" },
  { name: "Garuda Indonesia", code: "GA", country: "Indonesia" },
  { name: "Lion Air", code: "JT", country: "Indonesia" },
  { name: "AirAsia", code: "AK", country: "Malaysia" },
  { name: "Scoot", code: "TR", country: "Singapore" },
  { name: "Bangkok Airways", code: "PG", country: "Thailand" },
  { name: "Qantas", code: "QF", country: "Australia" },
  { name: "Virgin Australia", code: "VA", country: "Australia" },
  { name: "Jetstar Airways", code: "JQ", country: "Australia" },
  { name: "Air New Zealand", code: "NZ", country: "New Zealand" },
  { name: "Fiji Airways", code: "FJ", country: "Fiji" },
  { name: "South African Airways", code: "SA", country: "South Africa" },
  { name: "Ethiopian Airlines", code: "ET", country: "Ethiopia" },
  { name: "Kenya Airways", code: "KQ", country: "Kenya" },
  { name: "EgyptAir", code: "MS", country: "Egypt" },
  { name: "Royal Air Maroc", code: "AT", country: "Morocco" },
  { name: "Tunisair", code: "TU", country: "Tunisia" },
  { name: "Royal Jordanian", code: "RJ", country: "Jordan" },
  { name: "Gulf Air", code: "GF", country: "Bahrain" },
  { name: "Kuwait Airways", code: "KU", country: "Kuwait" },
  { name: "Oman Air", code: "WY", country: "Oman" },
  { name: "Saudia", code: "SV", country: "Saudi Arabia" },
  { name: "flydubai", code: "FZ", country: "United Arab Emirates" },
  { name: "Air Arabia", code: "G9", country: "United Arab Emirates" },
  { name: "El Al Israel Airlines", code: "LY", country: "Israel" },
  { name: "Pakistan International Airlines", code: "PK", country: "Pakistan" },
  { name: "Biman Bangladesh Airlines", code: "BG", country: "Bangladesh" },
  { name: "SriLankan Airlines", code: "UL", country: "Sri Lanka" },
  { name: "Uzbekistan Airways", code: "HY", country: "Uzbekistan" },
  { name: "Air Astana", code: "KC", country: "Kazakhstan" },
  { name: "Hawaiian Airlines", code: "HA", country: "United States" },
  { name: "Virgin Atlantic", code: "VS", country: "United Kingdom" },
  { name: "Eurowings", code: "EW", country: "Germany" },
  { name: "Condor", code: "DE", country: "Germany" },
  { name: "Transavia", code: "HV", country: "Netherlands" },
  { name: "Air Europa", code: "UX", country: "Spain" },
  { name: "Royal Brunei Airlines", code: "BI", country: "Brunei" },
  { name: "Myanmar Airways International", code: "8M", country: "Myanmar" },
  { name: "Druk Air", code: "KB", country: "Bhutan" },
  { name: "Maldivian", code: "Q2", country: "Maldives" },
  { name: "Starlux Airlines", code: "JX", country: "Taiwan" },
  { name: "Zipair Tokyo", code: "ZG", country: "Japan" },
  { name: "Akasa Air", code: "QP", country: "India" },
  { name: "Bamboo Airways", code: "QH", country: "Vietnam" },
  { name: "Breeze Airways", code: "MX", country: "United States" },
  { name: "PLAY", code: "OG", country: "Iceland" },
  { name: "Norse Atlantic Airways", code: "N0", country: "Norway" },
  { name: "flynas", code: "XY", country: "Saudi Arabia" },
  { name: "Jazeera Airways", code: "J9", country: "Kuwait" },
  { name: "SalamAir", code: "OV", country: "Oman" },
  { name: "Air Premia", code: "YP", country: "South Korea" },
  { name: "Shree Airlines", code: "N9", country: "Nepal" },
  { name: "12 North", code: "12", country: "India" },
  { name: "1Time Airline", code: "1T", country: "South Africa" },
  { name: "40-Mile Air", code: "Q5", country: "United States" },
  { name: "88", code: "47", country: "Cyprus" },
  { name: "Abacus International", code: "1B", country: "Singapore" },
  { name: "ABSA - Aerolinhas Brasileiras", code: "M3", country: "Brazil" },
  { name: "Abu Dhabi Amiri Flight", code: "MO", country: "United Arab Emirates" },
  { name: "Access Air", code: "ZA", country: "United States" },
  { name: "Ada Air", code: "ZY", country: "Albania" },
  { name: "Adam Air", code: "KI", country: "Indonesia" },
  { name: "Adria Airways", code: "JP", country: "Slovenia" },
  { name: "Aer Arann", code: "RE", country: "Ireland" },
  { name: "Aereonautica militare", code: "JY", country: "Italy" },
  { name: "Aero Benin", code: "EM", country: "Benin" },
  { name: "Aero Condor Peru", code: "Q6", country: "Peru" },
  { name: "Aero Contractors", code: "AJ", country: "Nigeria" },
  { name: "Aero Flight", code: "GV", country: "Germany" },
  { name: "Aero Lanka", code: "QL", country: "Sri Lanka" },
  { name: "Aero VIP (2D)", code: "2D", country: "Portugal" },
  { name: "Aero-Service", code: "BF", country: "Republic of the Congo" },
  { name: "Aerocondor", code: "2B", country: "Portugal" },
  { name: "Aeroflot-Don", code: "D9", country: "Russia" },
  { name: "Aeroflot-Nord", code: "5N", country: "Russia" },
  { name: "Aerolane", code: "XL", country: "Ecuador" },
  { name: "Aeroline GmbH", code: "7E", country: "Germany" },
  { name: "Aerolineas Galapagos (Aerogal)", code: "2K", country: "Ecuador" },
  { name: "Aerolitoral", code: "5D", country: "Mexico" },
  { name: "Aeromar", code: "VW", country: "Mexico" },
  { name: "Aeropelican Air Services", code: "OT", country: "Australia" },
  { name: "Aeroper", code: "PL", country: "Peru" },
  { name: "AeroRep", code: "P5", country: "Colombia" },
  { name: "Aerosur", code: "5L", country: "Bolivia" },
  { name: "Aerosvit Airlines", code: "VV", country: "Ukraine" },
  { name: "AeroWorld", code: "W4", country: "Russia" },
  { name: "Africa West", code: "FK", country: "Togo" },
  { name: "Afriqiyah Airways", code: "8U", country: "Libya" },
  { name: "Aigle Azur", code: "ZI", country: "France" },
  { name: "Air Afrique", code: "RK", country: "Ivory Coast" },
  { name: "Air Algerie", code: "AH", country: "Algeria" },
  { name: "Air Alps Aviation (A6)", code: "A6", country: "Austria" },
  { name: "Air Antilles Express", code: "3S", country: "Guadeloupe" },
  { name: "Air Arabia Egypt", code: "E5", country: "Egypt" },
  { name: "Air Arabia Maroc", code: "3O", country: "Morocco" },
  { name: "Air Atlanta Icelandic", code: "CC", country: "Iceland" },
  { name: "Air Austral", code: "UU", country: "France" },
  { name: "Air Bagan", code: "W9", country: "Myanmar" },
  { name: "Air Baltic", code: "BT", country: "Latvia" },
  { name: "Air Bangladesh", code: "B9", country: "Bangladesh" },
  { name: "Air Berlin", code: "AB", country: "Germany" },
  { name: "Air Bosna", code: "JA", country: "Bosnia and Herzegovina" },
  { name: "Air Botswana", code: "BP", country: "Botswana" },
  { name: "Air Bourbon", code: "ZB", country: "Reunion" },
  { name: "Air Burkina", code: "2J", country: "Burkina Faso" },
  { name: "Air Busan", code: "BX", country: "Republic of Korea" },
  { name: "Air Caledonie International", code: "SB", country: "France" },
  { name: "Air Canada Jazz", code: "QK", country: "Canada" },
  { name: "Air Caraïbes", code: "TX", country: "France" },
  { name: "Air Cargo Carriers", code: "2Q", country: "United States" },
  { name: "Air Cargo Germany", code: "6U", country: "Germany" },
  { name: "Air Carnival", code: "2S", country: "India" },
  { name: "Air Chathams", code: "CV", country: "New Zealand" },
  { name: "Air Choice One", code: "3E", country: "United States" },
  { name: "Air Comet Chile", code: "3I", country: "Chile" },
  { name: "Air Costa", code: "LB", country: "India" },
  { name: "Air Dolomiti", code: "EN", country: "Italy" },
  { name: "Air Europe", code: "PE", country: "Italy" },
  { name: "Air Exel", code: "XT", country: "Netherlands" },
  { name: "Air Finland", code: "OF", country: "Finland" },
  { name: "Air Foyle", code: "GS", country: "United Kingdom" },
  { name: "Air Glaciers", code: "7T", country: "Switzerland" },
  { name: "Air Greenland", code: "GL", country: "Denmark" },
  { name: "Air Guinee Express", code: "2U", country: "Guinea" },
  { name: "Air Guyane", code: "GG", country: "French Guiana" },
  { name: "Air Hamburg (AHO)", code: "HH", country: "Germany" },
  { name: "Air Iceland", code: "NY", country: "Iceland" },
  { name: "Air India Express", code: "IX", country: "India" },
  { name: "Air India Regional", code: "CD", country: "India" },
  { name: "Air Indus", code: "PP", country: "Pakistan" },
  { name: "Air Italy", code: "I9", country: "Italy" },
  { name: "Air Ivoire", code: "VU", country: "Ivory Coast" },
  { name: "Air Jamaica", code: "JM", country: "Jamaica" },
  { name: "Air Japan", code: "NQ", country: "Japan" },
  { name: "Air Kazakhstan", code: "9Y", country: "Kazakhstan" },
  { name: "Air Kiribati", code: "4A", country: "Kiribati" },
  { name: "Air Koryo", code: "JS", country: "Democratic People's Republic of Korea" },
  { name: "Air Libert", code: "VD", country: "France" },
  { name: "Air Lituanica", code: "LT", country: "Lithuania" },
  { name: "Air Luxor", code: "LK", country: "Portugal" },
  { name: "Air Macau", code: "NX", country: "Macao" },
  { name: "Air Madagascar", code: "MD", country: "Madagascar" },
  { name: "Air Madrid", code: "NM", country: "Spain" },
  { name: "Air Malawi", code: "QM", country: "Malawi" },
  { name: "Air Malta", code: "KM", country: "Malta" },
  { name: "Air Mandalay", code: "6T", country: "Burma" },
  { name: "Air Marshall Islands", code: "CW", country: "Marshall Islands" },
  { name: "Air Mauritius", code: "MK", country: "Mauritius" },
  { name: "Air Mediterranee", code: "DR", country: "France" },
  { name: "Air Mekong", code: "P8", country: "Vietnam" },
  { name: "Air Moldova", code: "9U", country: "Moldova" },
  { name: "Air Mozambique", code: "TM", country: "Mozambique" },
  { name: "Air Namibia", code: "SW", country: "Namibia" },
  { name: "Air Nippon", code: "EL", country: "Japan" },
  { name: "Air Niugini", code: "PX", country: "Papua New Guinea" },
  { name: "Air North Charter - Canada", code: "4N", country: "Canada" },
  { name: "Air Nostrum", code: "YW", country: "Spain" },
  { name: "Air One", code: "AP", country: "Italy" },
  { name: "Air Pegasus", code: "OP", country: "India" },
  { name: "Air Philippines", code: "2P", country: "Philippines" },
  { name: "Air Plus Comet", code: "A7", country: "Spain" },
  { name: "Air Rarotonga", code: "GZ", country: "Cook Islands" },
  { name: "Air Sahara", code: "S2", country: "India" },
  { name: "Air Saint Pierre", code: "PJ", country: "France" },
  { name: "Air Salone", code: "2O", country: "Sierra Leone" },
  { name: "Air Seychelles", code: "HM", country: "Seychelles" },
  { name: "Air Sicilia", code: "BM", country: "Italy" },
  { name: "Air Sinai", code: "4D", country: "Egypt" },
  { name: "Air Tahiti", code: "VT", country: "French Polynesia" },
  { name: "Air Tahiti Nui", code: "TN", country: "France" },
  { name: "Air Tanzania", code: "TC", country: "Tanzania" },
  { name: "Air Tindi", code: "8T", country: "Canadian Territories" },
  { name: "Air Transat", code: "TS", country: "Canada" },
  { name: "Air Vanuatu", code: "NF", country: "Vanuatu" },
  { name: "Air VIA", code: "VL", country: "Bulgaria" },
  { name: "Air Volga", code: "G6", country: "Russia" },
  { name: "Air Wales", code: "6G", country: "United Kingdom" },
  { name: "Air Wisconsin", code: "ZW", country: "United States" },
  { name: "Air Zimbabwe", code: "UM", country: "Zimbabwe" },
  { name: "Air2there", code: "F8", country: "New Zealand" },
  { name: "AirAsia X", code: "D7", country: "Malaysia" },
  { name: "Airblue", code: "ED", country: "Pakistan" },
  { name: "Aircompany Yakutia", code: "R3", country: "Russia" },
  { name: "Aires", code: "4C", country: " S.A." },
  { name: "Airlinair", code: "A5", country: "France" },
  { name: "Airlines Of Tasmania", code: "FO", country: "Australia" },
  { name: "Airlines PNG", code: "CG", country: "Papua New Guinea" },
  { name: "Airlink (SAA)", code: "4Z", country: "South Africa" },
  { name: "Airnorth", code: "TL", country: "Australia" },
  { name: "AirRussia", code: "R8", country: "Russia" },
  { name: "AirTran Airways", code: "FL", country: "United States" },
  { name: "Al-Naser Airlines", code: "NA", country: "Iraq" },
  { name: "ALAK", code: "J4", country: "Russia" },
  { name: "Alaska Central Express", code: "KO", country: "United States" },
  { name: "Alaska Seaplane Service", code: "J5", country: "United States" },
  { name: "Albanian Airlines", code: "LV", country: "Albania" },
  { name: "Alitalia Cityliner", code: "CT", country: "Italy" },
  { name: "Alitalia Express", code: "XM", country: "Italy" },
  { name: "All Africa", code: "9A", country: "South Africa" },
  { name: "All America", code: "A2", country: "United States" },
  { name: "All America AR", code: "2R", country: "Argentina" },
  { name: "All America BOPY", code: "0P", country: "Paraguay" },
  { name: "All America BR", code: "1Y", country: "Brazil" },
  { name: "All America CL", code: "1R", country: "Chile" },
  { name: "All America CO", code: "0Y", country: "Colombia" },
  { name: "All America MX", code: "0M", country: "Mexico" },
  { name: "All America US", code: "AG", country: "United States" },
  { name: "All Argentina", code: "L1", country: "Argentina" },
  { name: "All Argentina Express", code: "Z0", country: "Argentina" },
  { name: "All Asia", code: "L9", country: "China" },
  { name: "All Australia", code: "88", country: "Australia" },
  { name: "All Colombia", code: "7O", country: "Colombia" },
  { name: "All Spain", code: "N7", country: "Spain" },
  { name: "Allegiant Air", code: "G4", country: "United States" },
  { name: "Alliance Airlines", code: "QQ", country: "Australia" },
  { name: "AlMasria Universal Airlines", code: "UJ", country: "Egypt" },
  { name: "Aloha Airlines", code: "AQ", country: "United States" },
  { name: "Alrosa Mirny Air Enterprise", code: "6R", country: "Russia" },
  { name: "Amaszonas", code: "Z8", country: "Bolivia" },
  { name: "America West Airlines", code: "HP", country: "United States" },
  { name: "American Eagle Airlines", code: "MQ", country: "United States" },
  { name: "Amsterdam Airlines", code: "WD", country: "Netherlands" },
  { name: "Ansett Australia", code: "AN", country: "Australia" },
  { name: "Apache Air", code: "ZM", country: "United States" },
  { name: "Ariana Afghan Airlines", code: "FG", country: "Afghanistan" },
  { name: "Arik Niger", code: "Q9", country: "Niger" },
  { name: "Arkefly", code: "OR", country: "Netherlands" },
  { name: "Arkia Israel Airlines", code: "IZ", country: "Israel" },
  { name: "Armavia", code: "U8", country: "Armenia" },
  { name: "Arrow Air", code: "JW", country: "United States" },
  { name: "Aserca Airlines", code: "R7", country: "Venezuela" },
  { name: "Asia Wings", code: "Y5", country: "Kazakhstan" },
  { name: "Asian Spirit", code: "6K", country: "Philippines" },
  { name: "Asian Wings Airways", code: "AW", country: "Burma" },
  { name: "Askari Aviation", code: "4K", country: "Pakistan" },
  { name: "Astair", code: "8D", country: "Russian Federation" },
  { name: "Astraeus", code: "5W", country: "United Kingdom" },
  { name: "Astrakhan Airlines", code: "OB", country: "Russia" },
  { name: "Astral Aviation", code: "8V", country: "Kenya" },
  { name: "ATA Airlines (Iran)", code: "I3", country: "Iran" },
  { name: "Athens Airways", code: "ZF", country: "Greece" },
  { name: "Atifly", code: "A1", country: "United States" },
  { name: "Atlant-Soyuz Airlines", code: "3G", country: "Russia" },
  { name: "Atlantic Airways", code: "RC", country: "Faroe Islands" },
  { name: "Atlantic Southeast Airlines", code: "EV", country: "United States" },
  { name: "Atlantis European Airways", code: "TD", country: "Armenia" },
  { name: "Atlas Air", code: "5Y", country: "United States" },
  { name: "Atlas Blue", code: "8A", country: "Morocco" },
  { name: "Atlasjet", code: "KK", country: "Turkey" },
  { name: "ATRAN Cargo Airlines", code: "V8", country: "Russian Federation" },
  { name: "Augsburg Airways", code: "IQ", country: "Germany" },
  { name: "Aurigny Air Services", code: "GR", country: "United Kingdom" },
  { name: "Austral Brasil", code: "W7", country: "Brazil" },
  { name: "Austral Lineas Aereas", code: "AU", country: "Argentina" },
  { name: "Aviabus", code: "U1", country: "Russia" },
  { name: "Avialeasing Aviation Company", code: "EC", country: "Uzbekistan" },
  { name: "Avianova (Russia)", code: "AO", country: "Russia" },
  { name: "Avient Aviation", code: "Z3", country: "Zimbabwe" },
  { name: "Avies", code: "U3", country: "Estonia" },
  { name: "Aws express", code: "B0", country: "United States" },
  { name: "Azerbaijan Airlines", code: "J2", country: "Azerbaijan" },
  { name: "BA CityFlyer", code: "CJ", country: "United Kingdom" },
  { name: "Bahamasair", code: "UP", country: "Bahamas" },
  { name: "Baikotovitchestrian Airlines", code: "BU", country: "American Samoa" },
  { name: "Balkan Bulgarian Airlines", code: "LZ" },
  { name: "Baltic Air lines", code: "B1", country: "Latvia" },
  { name: "Barents AirLink", code: "8N", country: "Sweden" },
  { name: "Bassaka airlines", code: "5B", country: "Cambodia" },
  { name: "Bearskin Lake Air Service", code: "JV", country: "Canada" },
  { name: "Belair Airlines", code: "4T", country: "Switzerland" },
  { name: "Belavia Belarusian Airlines", code: "B2", country: "Belarus" },
  { name: "Bellview Airlines", code: "B3", country: "Nigeria" },
  { name: "Bemidji Airlines", code: "CH", country: "United States" },
  { name: "Bering Air", code: "8E", country: "United States" },
  { name: "Berjaya Air", code: "J8", country: "Malaysia" },
  { name: "Binter Canarias", code: "NT", country: "Spain" },
  { name: "Black Stallion Airways", code: "BZ", country: "United States" },
  { name: "Blue Air", code: "0B", country: "Romania" },
  { name: "Blue Panorama Airlines", code: "BV", country: "Italy" },
  { name: "Blue Wings", code: "QW", country: "Germany" },
  { name: "Blue1", code: "KF", country: "Finland" },
  { name: "bmi", code: "BD", country: "United Kingdom" },
  { name: "bmibaby", code: "WW", country: "United Kingdom" },
  { name: "Bobb Air Freight", code: "01", country: "Germany" },
  { name: "Boutique Air (Priv)", code: "4B", country: "United States" },
  { name: "BQB Lineas Aereas", code: "5Q", country: "Uruguay" },
  { name: "BRAZIL AIR", code: "GB", country: "Brazil" },
  { name: "Brit Air", code: "DB", country: "France" },
  { name: "British International Helicopters", code: "BS", country: "United Kingdom" },
  { name: "British Mediterranean Airways", code: "KJ", country: "United Kingdom" },
  { name: "BudgetAir", code: "1K", country: "Germany" },
  { name: "Bulgaria Air", code: "FB", country: "Bulgaria" },
  { name: "Buquebus Líneas Aéreas", code: "BQ", country: "Uruguay" },
  { name: "Business Aviation", code: "4P", country: "Congo (Kinshasa)" },
  { name: "BusinessAir", code: "8B", country: "Thailand" },
  { name: "BVI Airways", code: "XV", country: "British Virgin Islands" },
  { name: "CAL Cargo Air Lines", code: "5C", country: "Israel" },
  { name: "Calima Aviacion", code: "XG", country: "Spain" },
  { name: "Camair-co", code: "QC", country: "Cameroon" },
  { name: "Cambodia Angkor Air (K6)", code: "K6", country: "Cambodia" },
  { name: "Canadian Airlines", code: "CP", country: "Canada" },
  { name: "Canadian National Airways", code: "CN", country: "Canada" },
  { name: "Canadian North", code: "5T", country: "Canada" },
  { name: "CanXplorer", code: "C2", country: "Canada" },
  { name: "CanXpress", code: "C1", country: "Canada" },
  { name: "Cape Air", code: "9K", country: "United States" },
  { name: "Cargo Plus Aviation", code: "8L", country: "United Arab Emirates" },
  { name: "Caribbean Airlines", code: "BW", country: "Trinidad and Tobago" },
  { name: "Carnival Air Lines", code: "KW", country: "United States" },
  { name: "Carpatair", code: "V3", country: "Romania" },
  { name: "Caspian Airlines", code: "RV", country: "Iran" },
  { name: "Catovair", code: "OC", country: "Mauritius" },
  { name: "Caucasus Airlines", code: "NS", country: "Georgia" },
  { name: "Cayman Airways", code: "KX", country: "Cayman Islands" },
  { name: "CB Airways UK ( Interliging Flights )", code: "1F", country: "United Kingdom" },
  { name: "CCML Airlines", code: "CB", country: "Colombia" },
  { name: "Centralwings", code: "C0", country: "Poland" },
  { name: "Chautauqua Airlines", code: "RP", country: "United States" },
  { name: "China Northwest Airlines (WH)", code: "WH", country: "China" },
  { name: "China SSS", code: "9C", country: "China" },
  { name: "China United", code: "KN", country: "China" },
  { name: "China United Airlines", code: "HR", country: "China" },
  { name: "Chongqing Airlines", code: "OQ", country: "China" },
  { name: "Ciao Air", code: "99", country: "Italy" },
  { name: "Ciel Canadien", code: "YC", country: "Canada" },
  { name: "Cimber Air", code: "QI", country: "Denmark" },
  { name: "Cirrus Airlines", code: "C9", country: "Germany" },
  { name: "Citilink Indonesia", code: "QG", country: "Indonesia" },
  { name: "City Airline", code: "CF", country: "Sweden" },
  { name: "City Airways", code: "E8", country: "Thailand" },
  { name: "CityJet", code: "WX", country: "Ireland" },
  { name: "Click (Mexicana)", code: "QA", country: "Mexico" },
  { name: "Coastal Air", code: "DQ", country: "United States" },
  { name: "Colgan Air", code: "9L", country: "United States" },
  { name: "Comair", code: "OH", country: "United States" },
  { name: "CommutAir", code: "C5", country: "United States" },
  { name: "Comores Airlines", code: "KR", country: "Comoros" },
  { name: "Compagnie Africaine d\\\\'Aviation", code: "E9", country: "Congo (Kinshasa)" },
  { name: "Congo Express", code: "XZ", country: "Congo (Kinshasa)" },
  { name: "Consorcio Aviaxsa", code: "6A", country: "Mexico" },
  { name: "Contact Air", code: "C3", country: "Germany" },
  { name: "Continental Airlines", code: "CO", country: "United States" },
  { name: "Continental Micronesia", code: "CS", country: "United States" },
  { name: "Conviasa", code: "V0", country: "Venezuela" },
  { name: "Copenhagen Express", code: "0X", country: "Denmark" },
  { name: "Corsairfly", code: "SS", country: "France" },
  { name: "Corse-Mediterranee", code: "XK", country: "France" },
  { name: "Cubana de Aviación", code: "CU", country: "Cuba" },
  { name: "Cyprus Airways", code: "CY", country: "Cyprus" },
  { name: "Cyprus Turkish Airlines", code: "YK", country: "Turkey" },
  { name: "Daallo Airlines", code: "D3", country: "Djibouti" },
  { name: "Dalavia", code: "H8", country: "Russia" },
  { name: "Dana Air", code: "DA", country: "Nigeria" },
  { name: "Danube Wings (V5)", code: "V5", country: "Slovakia" },
  { name: "Darwin Airline", code: "0D", country: "Switzerland" },
  { name: "DAT Danish Air Transport", code: "DX", country: "Denmark" },
  { name: "dba", code: "DI", country: "Germany" },
  { name: "Denim Air", code: "J7", country: "Norway" },
  { name: "Dennis Sky", code: "DH", country: "Israel" },
  { name: "Dense Airways", code: "KP", country: "United States" },
  { name: "Dense Connection", code: "KZ", country: "United States" },
  { name: "Deutsche Bahn", code: "2A", country: "Germany" },
  { name: "Djibouti Airlines", code: "D8", country: "Djibouti" },
  { name: "Dobrolet", code: "QD", country: "Russia" },
  { name: "Domenican Airlines", code: "D1", country: "Dominican Republic" },
  { name: "Dominicana de Aviaci", code: "DO", country: "Dominican Republic" },
  { name: "Domodedovo Airlines", code: "E3", country: "Russia" },
  { name: "Eagle Air", code: "H7", country: "Uganda" },
  { name: "Eagle Atlantic Airlines", code: "E2", country: "Ghana" },
  { name: "East African", code: "QU", country: "Uganda" },
  { name: "Eastar Jet", code: "ZE", country: "South Korea" },
  { name: "Eastern Airways", code: "T3", country: "United Kingdom" },
  { name: "Eastern Atlantic Virtual Airlines", code: "13", country: "United States" },
  { name: "Eastland Air", code: "DK", country: "Australia" },
  { name: "EasyJet (DS)", code: "DS", country: "Switzerland" },
  { name: "Edelweiss Air", code: "WK", country: "Switzerland" },
  { name: "El-Buraq Air Transport", code: "UZ", country: "Libya" },
  { name: "Elysian Airlines", code: "E4", country: "Cameroon" },
  { name: "Empresa Ecuatoriana De Aviacion", code: "EU", country: "Ecuador" },
  { name: "Epic Holiday", code: "FA", country: "United States" },
  { name: "Era Alaska", code: "7H", country: "United States" },
  { name: "Eritrean Airlines", code: "B8", country: "Eritrea" },
  { name: "Euro Exec Express", code: "RZ", country: "Sweden" },
  { name: "Euro Jet", code: "24", country: "Germany" },
  { name: "Eurocypria Airlines", code: "UI", country: "Cyprus" },
  { name: "Eurofly Service", code: "GJ", country: "Italy" },
  { name: "Euroline", code: "4L", country: "Georgia" },
  { name: "Eurolot", code: "K2", country: "Poland" },
  { name: "Europe Jet", code: "EX", country: "France" },
  { name: "European Air Express", code: "EA", country: "Germany" },
  { name: "EuropeSky", code: "ES", country: "Germany" },
  { name: "Evergreen International Airlines", code: "EZ", country: "United States" },
  { name: "Excel Airways", code: "JN", country: "United Kingdom" },
  { name: "Express One International", code: "EO", country: "United States" },
  { name: "ExpressJet", code: "XE", country: "United States" },
  { name: "Far Eastern Air Transport", code: "EF", country: "Taiwan" },
  { name: "Felix Airways", code: "FU", country: "Yemen" },
  { name: "Finncomm Airlines", code: "FC", country: "Finland" },
  { name: "Firefly", code: "FY", country: "Malaysia" },
  { name: "First Air", code: "7F", country: "Canada" },
  { name: "First Choice Airways", code: "DP", country: "United Kingdom" },
  { name: "Flightline", code: "B5", country: "United Kingdom" },
  { name: "Flightlink Tanzania", code: "Z9", country: "Tanzania" },
  { name: "Florida West International Airways", code: "RF", country: "United States" },
  { name: "Fly 6ix", code: "6I", country: "Sierra Leone" },
  { name: "Fly Brasil", code: "F1", country: "Brazil" },
  { name: "Fly Colombia ( Interliging Flights )", code: "3F", country: "Colombia" },
  { name: "Fly Europa", code: "ER", country: "Spain" },
  { name: "Fly France", code: "FF", country: "France" },
  { name: "Fly One", code: "F5", country: "Moldova" },
  { name: "Fly Romania", code: "X5", country: "Romania" },
  { name: "Fly540", code: "5H", country: "Kenya" },
  { name: "Flybaboo", code: "F7", country: "Switzerland" },
  { name: "Flybe", code: "BE", country: "United Kingdom" },
  { name: "Flyglobespan", code: "B4", country: "United Kingdom" },
  { name: "FlyHigh Airlines Ireland (FH)", code: "FH", country: "Ireland" },
  { name: "FlyLal", code: "TE", country: "Lithuania" },
  { name: "FlyNordic", code: "LF", country: "Sweden" },
  { name: "FlyPortugal", code: "PO", country: "Portugal" },
  { name: "FOX Linhas Aereas", code: "FX", country: "Brazil" },
  { name: "Freedom Air", code: "FP", country: "United States" },
  { name: "Frontier Flying Service", code: "2F", country: "United States" },
  { name: "Fuji Dream Airlines", code: "JH", country: "Japan" },
  { name: "Gabon Airlines", code: "GY", country: "Gabon" },
  { name: "Gadair European Airlines", code: "GP", country: "Spain" },
  { name: "Gazpromavia", code: "4G", country: "Russia" },
  { name: "GB Airways", code: "GT", country: "United Kingdom" },
  { name: "Genesis", code: "GK", country: "Pakistan" },
  { name: "Georgian Airways", code: "A9", country: "Georgia" },
  { name: "Georgian National Airlines", code: "QB", country: "Georgia" },
  { name: "German International Air Lines", code: "GM", country: "Germany" },
  { name: "Germania", code: "ST", country: "Germany" },
  { name: "Germanwings", code: "4U", country: "Germany" },
  { name: "GermanXL", code: "GX", country: "Germany" },
  { name: "Ghana International Airlines", code: "G0", country: "Ghana" },
  { name: "Global Airlines", code: "0G", country: "Argentina" },
  { name: "Globus", code: "GH", country: "Russia" },
  { name: "GNB Linhas Aereas", code: "GN", country: "Brazil" },
  { name: "Go Air", code: "G8", country: "India" },
  { name: "GoJet Airlines", code: "G7", country: "United States" },
  { name: "Golden Air", code: "DC", country: "Sweden" },
  { name: "Gomelavia", code: "YD", country: "Belarus" },
  { name: "Great Lakes Airlines", code: "ZK", country: "United States" },
  { name: "Greenfly", code: "XX", country: "Spain" },
  { name: "Grupo TACA", code: "TA", country: "Costa Rica" },
  { name: "Gryphon Airlines", code: "6P", country: "United States" },
  { name: "Hageland Aviation Services", code: "H6", country: "United States" },
  { name: "Haiti Ambassador Airlines", code: "2T", country: "Haiti" },
  { name: "Halcyonair", code: "7Z", country: "Cape Verde" },
  { name: "Hamburg International", code: "4R", country: "Germany" },
  { name: "Hankook Air US", code: "H1", country: "United States" },
  { name: "Hankook Airline", code: "HN", country: "South Korea" },
  { name: "Hapagfly", code: "HF", country: "Germany" },
  { name: "Harbour Air (Priv)", code: "H3", country: "Canada" },
  { name: "Hawkair", code: "BH", country: "Canada" },
  { name: "Heli France", code: "8H", country: "France" },
  { name: "Helijet", code: "JB", country: "Canada" },
  { name: "Hellas Jet", code: "T4", country: "Greece" },
  { name: "Hellenic Imperial Airways", code: "HT", country: "Greece" },
  { name: "Hello", code: "HW", country: "Switzerland" },
  { name: "Helvetic Airways", code: "2L", country: "Switzerland" },
  { name: "Hex'Air", code: "UD", country: "France" },
  { name: "Hi Fly (5K)", code: "5K", country: "Portugal" },
  { name: "Hokkaido International Airlines", code: "HD", country: "Japan" },
  { name: "Homer Air", code: "MR", country: "Germany" },
  { name: "Hong Kong Airlines", code: "HX", country: "Hong Kong SAR of China" },
  { name: "Hong Kong Express Airways", code: "UO", country: "Hong Kong SAR of China" },
  { name: "Horizon Air", code: "QX", country: "United States" },
  { name: "Horizon Airlines", code: "BN", country: "Australia" },
  { name: "Huaxia", code: "G5", country: "China" },
  { name: "I-Fly", code: "H5", country: "Russia" },
  { name: "Iberia Express", code: "I2", country: "Spain" },
  { name: "Iberworld", code: "TY", country: "Spain" },
  { name: "Ibex Airlines", code: "FW", country: "Japan" },
  { name: "Imair Airlines", code: "IK", country: "Azerbaijan" },
  { name: "INAVIA Internacional", code: "Z5", country: "Argentina" },
  { name: "Indian Airlines", code: "IC", country: "India" },
  { name: "Indonesia AirAsia", code: "QZ", country: "Indonesia" },
  { name: "Indonesia Sky", code: "I5", country: "Indonesia" },
  { name: "Indonesian Airlines", code: "IO", country: "Indonesia" },
  { name: "Indya Airline Group", code: "G1", country: "India" },
  { name: "Insel Air (7I/INC) (Priv)", code: "7I", country: "Netherlands Antilles" },
  { name: "Interair South Africa", code: "D6", country: "South Africa" },
  { name: "Interjet (ABC Aerolineas)", code: "4O", country: "Mexico" },
  { name: "Interlink Airlines", code: "ID", country: "South Africa" },
  { name: "International AirLink", code: "I4", country: "Jamaica" },
  { name: "International Europe", code: "9I", country: "Spain" },
  { name: "Intersky", code: "3L", country: "Austria" },
  { name: "Iran Air", code: "IR", country: "Iran" },
  { name: "Iran Aseman Airlines", code: "EP", country: "Iran" },
  { name: "Iraqi Airways", code: "IA", country: "Iraq" },
  { name: "Island Air (WP)", code: "WP", country: "United States" },
  { name: "Island Airlines", code: "IS", country: "United States" },
  { name: "Island Express Air", code: "1X", country: "Canada" },
  { name: "Island Spirit", code: "IP", country: "Iceland" },
  { name: "Islas Airways", code: "IF", country: "Spain" },
  { name: "Islena De Inversiones", code: "WC", country: "Honduras" },
  { name: "Israir", code: "6H", country: "Israel" },
  { name: "Itek Air", code: "GI", country: "Kyrgyzstan" },
  { name: "IzAvia", code: "I8", country: "Russia" },
  { name: "JAL Express", code: "JC", country: "Japan" },
  { name: "JALways", code: "JO", country: "Japan" },
  { name: "Japan Air System", code: "JD", country: "Japan" },
  { name: "Japan Asia Airways", code: "EG", country: "Japan" },
  { name: "Japan Regio", code: "ZX", country: "Japan" },
  { name: "Japan Transocean Air", code: "NU", country: "Japan" },
  { name: "Jeju Air", code: "7C", country: "Republic of Korea" },
  { name: "Jet Airways", code: "9W", country: "India" },
  { name: "Jet2.com", code: "LS", country: "United Kingdom" },
  { name: "Jet4You", code: "8J", country: "Morocco" },
  { name: "Jetairfly", code: "JF", country: "Belgium" },
  { name: "Jetgo Australia", code: "JG", country: "Australia" },
  { name: "Jetstar Asia Airways", code: "3K", country: "Singapore" },
  { name: "Jetstar Pacific", code: "BL", country: "Vietnam" },
  { name: "Jettor Airlines", code: "NR", country: "Hong Kong" },
  { name: "Jin Air", code: "LJ", country: "South Korea" },
  { name: "JobAir", code: "3B", country: "Czech Republic" },
  { name: "Joy Air", code: "JR", country: "China" },
  { name: "Juneyao Airlines", code: "HO", country: "China" },
  { name: "Kam Air", code: "RQ", country: "Afghanistan" },
  { name: "Kavminvodyavia", code: "KV", country: "Russia" },
  { name: "KD Avia", code: "KD", country: "Russia" },
  { name: "Kenmore Air", code: "M5", country: "United States" },
  { name: "Kharkiv Airlines", code: "KH", country: "Ukraine" },
  { name: "Kingfisher Airlines", code: "IT", country: "India" },
  { name: "Kish Air", code: "Y9", country: "Iran" },
  { name: "KLM Cityhopper", code: "WA", country: "Netherlands" },
  { name: "Kogalymavia Air Company", code: "7K", country: "Russia" },
  { name: "KoralBlue Airlines", code: "K7", country: "Egypt" },
  { name: "Korongo Airlines", code: "ZC", country: "Congo (Kinshasa)" },
  { name: "Kostromskie avialinii", code: "K1", country: "Russia" },
  { name: "Krasnojarsky Airlines", code: "7B", country: "Russia" },
  { name: "KSY", code: "KY", country: "Greece" },
  { name: "Kuban Airlines", code: "GW", country: "Russia" },
  { name: "Kuzu Airlines Cargo", code: "GO", country: "Turkey" },
  { name: "L", code: "MJ", country: "Argentina" },
  { name: "LACSA", code: "LR", country: "Costa Rica" },
  { name: "LAN Argentina", code: "4M", country: "Argentina" },
  { name: "LAN Express", code: "LU", country: "Chile" },
  { name: "LAN Peru", code: "LP", country: "Peru" },
  { name: "Lao Airlines", code: "QV", country: "Lao Peoples Democratic Republic" },
  { name: "Lauda Air", code: "NG", country: "Austria" },
  { name: "LCM AIRLINES", code: "LQ", country: "Russia" },
  { name: "Leeward Islands Air Transport", code: "LI", country: "Antigua and Barbuda" },
  { name: "Liberty Airways", code: "LE", country: "United States" },
  { name: "Libyan Arab Airlines", code: "LN", country: "Libya" },
  { name: "Line Blue", code: "L8", country: "Germany" },
  { name: "Linhas A", code: "LM", country: "Mozambique" },
  { name: "LionXpress", code: "C4", country: "Cameroon" },
  { name: "Locair", code: "ZQ", country: "United States" },
  { name: "LSM Airlines", code: "PQ", country: "Russia" },
  { name: "LSM AIRLINES", code: "YZ", country: "Russia" },
  { name: "LSM International", code: "II", country: "Russia" },
  { name: "LTE International Airways", code: "XO", country: "Spain" },
  { name: "LTU Austria", code: "L3", country: "Austria" },
  { name: "Luchsh Airlines", code: "L4", country: "Russia" },
  { name: "Luftfahrtgesellschaft Walter", code: "HE", country: "Germany" },
  { name: "Lufthansa CityLine", code: "CL", country: "Germany" },
  { name: "Lufttransport", code: "L5", country: "Norway" },
  { name: "Lugansk Airlines", code: "L7", country: "Ukraine" },
  { name: "Luxair", code: "LG", country: "Luxembourg" },
  { name: "Maastricht Airlines", code: "W2", country: "Netherlands" },
  { name: "Maersk", code: "DM", country: "Denmark" },
  { name: "Mahan Air", code: "W5", country: "Iran" },
  { name: "Malawian Airlines", code: "3W", country: "Malawi" },
  { name: "Maldivo Airlines", code: "ML", country: "Maldives" },
  { name: "Malév", code: "MA", country: "Hungary" },
  { name: "Malindo Air", code: "OD", country: "Malaysia" },
  { name: "Malmö Aviation", code: "TF", country: "Sweden" },
  { name: "Malta Air Charter", code: "R5", country: "Malta" },
  { name: "Mandala Airlines", code: "RI", country: "Indonesia" },
  { name: "Mandarin Airlines", code: "AE", country: "Taiwan" },
  { name: "Mango", code: "JE", country: "South Africa" },
  { name: "Martinair", code: "MP", country: "Netherlands" },
  { name: "Marusya Airways", code: "Y8", country: "Russia" },
  { name: "Maryland Air", code: "M1", country: "United States" },
  { name: "Marysya Airlines", code: "M4", country: "Russia" },
  { name: "MasAir", code: "M7", country: "Mexico" },
  { name: "MAT Airways", code: "6F", country: "Macedonia" },
  { name: "MAT Macedonian Airlines", code: "IN", country: "Macedonia" },
  { name: "Mauritania Airlines International", code: "L6", country: "Mauritania" },
  { name: "Maya Island Air", code: "MW", country: "Belize" },
  { name: "MDLR Airlines", code: "9H", country: "India" },
  { name: "Med Airways", code: "7Y", country: "Lebanon" },
  { name: "Meridiana", code: "IG", country: "Italy" },
  { name: "Merpati Nusantara Airlines", code: "MZ", country: "Indonesia" },
  { name: "Mesa Airlines", code: "YV", country: "United States" },
  { name: "Mesaba Airlines", code: "XJ", country: "United States" },
  { name: "Metro Batavia", code: "7P", country: "Indonesia" },
  { name: "MexicanaLink", code: "I6", country: "Mexico" },
  { name: "MHS Aviation GmbH", code: "M2", country: "Germany" },
  { name: "MIAT Mongolian Airlines", code: "OM", country: "Mongolia" },
  { name: "Michael Airlines", code: "DF", country: "Puerto Rico" },
  { name: "Middle East Airlines", code: "ME", country: "Lebanon" },
  { name: "Midway Airlines", code: "JI", country: "United States" },
  { name: "Midwest Airlines", code: "YX", country: "United States" },
  { name: "Midwest Airlines (Egypt)", code: "MY", country: "Egypt" },
  { name: "MNG Airlines", code: "MB", country: "Turkey" },
  { name: "Moldavian Airlines", code: "2M", country: "Moldova" },
  { name: "Mongolian International Air Lines", code: "7M", country: "Mongolia" },
  { name: "Montenegro Airlines", code: "YM", country: "Montenegro" },
  { name: "Moskovia Airlines", code: "3R", country: "Russia" },
  { name: "Motor Sich", code: "M9", country: "Ukraine" },
  { name: "Myanma Airways", code: "UB", country: "Myanmar" },
  { name: "MyTravel Airways", code: "VZ", country: "United Kingdom" },
  { name: "Myway Airlines", code: "8I", country: "Italy" },
  { name: "N1", code: "N1", country: "Peru" },
  { name: "Nasair", code: "UE", country: "Eritrea" },
  { name: "National Air Cargo", code: "N8", country: "United States" },
  { name: "National Jet Systems", code: "NC", country: "Australia" },
  { name: "Nationwide Airlines", code: "CE", country: "South Africa" },
  { name: "Nauru Air Corporation", code: "ON", country: "Nauru" },
  { name: "NetJets", code: "1I", country: "United States" },
  { name: "New England Airlines", code: "EJ", country: "United States" },
  { name: "NEXT Brasil", code: "XB", country: "Brazil" },
  { name: "NextJet", code: "2N", country: "Sweden" },
  { name: "Niki", code: "HG", country: "Austria" },
  { name: "Nile Air", code: "NP", country: "Egypt" },
  { name: "Nok Air", code: "DD", country: "Thailand" },
  { name: "Nordic Global Airlines", code: "NJ", country: "Finland" },
  { name: "Nordica", code: "EE", country: "Estonia" },
  { name: "NordStar Airlines", code: "Y7", country: "Russia" },
  { name: "Northern Dene Airways", code: "U7", country: "Canada" },
  { name: "Northwest Airlines", code: "NW", country: "United States" },
  { name: "Northwestern Air", code: "J3", country: "Canada" },
  { name: "Norwegian Long Haul AS", code: "DU", country: "Norway" },
  { name: "Nouvel Air Tunisie", code: "BJ", country: "Tunisia" },
  { name: "Oasis Hong Kong Airlines", code: "O8", country: "Hong Kong" },
  { name: "Oceanair", code: "O6", country: "Brazil" },
  { name: "Oceanic Airlines", code: "O2", country: "Guinea" },
  { name: "Olympic Airlines", code: "OA", country: "Greece" },
  { name: "Omni Air International", code: "OY", country: "United States" },
  { name: "OneChina", code: "1C", country: "China" },
  { name: "OneJet", code: "J1", country: "United States" },
  { name: "Onur Air", code: "8Q", country: "Turkey" },
  { name: "Orbit Airlines Azerbaijan", code: "O1", country: "Azerbaijan" },
  { name: "Orchid Airlines", code: "OI", country: "Australia" },
  { name: "Orenburg Airlines", code: "R2", country: "Russia" },
  { name: "Orient Thai Airlines", code: "OX", country: "Thailand" },
  { name: "Origin Pacific Airways", code: "QO", country: "New Zealand" },
  { name: "Ostfriesische Lufttransport", code: "OL", country: "Germany" },
  { name: "Overland Airways", code: "OJ", country: "Nigeria" },
  { name: "Ozjet Airlines", code: "O7", country: "Australia" },
  { name: "Pacific Coastal Airline", code: "8P", country: "Canada" },
  { name: "Pacific East Asia Cargo Airlines", code: "Q8", country: "Philippines" },
  { name: "Pacific Wings", code: "LW", country: "United States" },
  { name: "Pal airlines", code: "5P", country: "Chile" },
  { name: "PAN Air", code: "PV", country: "Spain" },
  { name: "Pan Am World Airways Dominicana", code: "7Q", country: "Dominican Republic" },
  { name: "PanAm World Airways", code: "WQ", country: "United States" },
  { name: "Papillon Grand Canyon Helicopters", code: "HI", country: "United States" },
  { name: "Paramount Airways", code: "I7", country: "India" },
  { name: "Parmiss Airlines (IPV)", code: "PA", country: "Iran" },
  { name: "Patriot Airways", code: "P4", country: "United States" },
  { name: "PB Air", code: "9Q", country: "Thailand" },
  { name: "Peach Aviation", code: "MM", country: "Japan" },
  { name: "Pelita", code: "6D", country: "Indonesia" },
  { name: "Peninsula Airways", code: "KS", country: "United States" },
  { name: "Peruvian Airlines", code: "P9", country: "Peru" },
  { name: "Piedmont Airlines (1948-1989)", code: "PI", country: "United States" },
  { name: "Pinnacle Airlines", code: "9E", country: "United States" },
  { name: "PLUNA", code: "PU", country: "Uruguay" },
  { name: "Polet Airlines (Priv)", code: "YQ", country: "Russia" },
  { name: "Polynesian Airlines", code: "PH", country: "Samoa" },
  { name: "Porter Airlines", code: "PD", country: "Canada" },
  { name: "Portugalia", code: "NI", country: "Portugal" },
  { name: "Potomac Air", code: "BK", country: "United States" },
  { name: "Precision Air", code: "PW", country: "Tanzania" },
  { name: "Primera Air", code: "PF", country: "Iceland" },
  { name: "Proflight Commuter Services", code: "P0", country: "Zambia" },
  { name: "RACSA", code: "R6", country: "Guatemala" },
  { name: "Rainbow Air (RAI)", code: "RN", country: "United States" },
  { name: "Rainbow Air Canada", code: "RY", country: "Canada" },
  { name: "Rainbow Air Euro", code: "RU", country: "United Kingdom" },
  { name: "Rainbow Air Polynesia", code: "RX", country: "United States" },
  { name: "Rainbow Air US", code: "RM", country: "United States" },
  { name: "Real Tonga", code: "RT", country: "Tonga" },
  { name: "Red Jet Andes", code: "PT", country: "Peru" },
  { name: "Red Jet Canada", code: "QY", country: "Canada" },
  { name: "Red Jet Mexico", code: "4X", country: "Mexico" },
  { name: "Red Wings", code: "WZ", country: "Russia" },
  { name: "REDjet", code: "Z7", country: "Barbados" },
  { name: "Régional", code: "YS", country: "France" },
  { name: "Regional Air Iceland", code: "9N", country: "Iceland" },
  { name: "Regional Airlines", code: "FN", country: "Morocco" },
  { name: "Regional Express", code: "ZL", country: "Australia" },
  { name: "Regional Paraguaya", code: "P7", country: "Paraguay" },
  { name: "Regionalia Chile", code: "9J", country: "Chile" },
  { name: "Regionalia México", code: "N4", country: "Mexico" },
  { name: "Regionalia Uruguay", code: "2X", country: "Uruguay" },
  { name: "Regionalia Venezuela", code: "9X", country: "Venezuela" },
  { name: "Republic Airlines", code: "RW", country: "United States" },
  { name: "Republic Express Airlines", code: "RH", country: "Indonesia" },
  { name: "REXAIR VIRTUEL", code: "RR", country: "France" },
  { name: "Rossiya", code: "R4", country: "Russia" },
  { name: "Rossiya-Russian Airlines", code: "FV", country: "Russia" },
  { name: "Royal Airways", code: "KG", country: "United States" },
  { name: "Royal European Airlines", code: "69", country: "United Kingdom" },
  { name: "Royal Falcon", code: "RL", country: "Jordan" },
  { name: "Rwandair Express", code: "WB", country: "Rwanda" },
  { name: "Ryan International Airlines", code: "RD", country: "United States" },
  { name: "S7 Airlines", code: "S7", country: "Russia" },
  { name: "Safi Airlines", code: "4Q", country: "Afghanistan" },
  { name: "Salmon Air", code: "S6", country: "United States" },
  { name: "Salsa d\\\\'Haiti", code: "SO", country: "Haiti" },
  { name: "Salzburg arrows", code: "SZ", country: "Austria" },
  { name: "Sama Airlines", code: "ZS", country: "Saudi Arabia" },
  { name: "Santa Barbara Airlines", code: "S3", country: "Venezuela" },
  { name: "Saratov Aviation Division", code: "6W", country: "Russia" },
  { name: "Sat Airlines", code: "HZ", country: "Kazakhstan" },
  { name: "SATA Air Acores", code: "SP", country: "Portugal" },
  { name: "SATA International", code: "S4", country: "Portugal" },
  { name: "SATENA", code: "9R", country: "Colombia" },
  { name: "Scat Air", code: "DV", country: "Kazakhstan" },
  { name: "Seaborne Airlines", code: "BB", country: "United States" },
  { name: "SeaPort Airlines", code: "K5", country: "United States" },
  { name: "Senegal Airlines", code: "DN", country: "Senegal" },
  { name: "SENIC AIRLINES", code: "YR", country: "United States" },
  { name: "Serbian Airlines", code: "S1", country: "Serbia" },
  { name: "Servicios de Transportes A", code: "FS", country: "Argentina" },
  { name: "Severstal Air Company", code: "D2", country: "Russia" },
  { name: "SGA Airlines", code: "5E", country: "Thailand" },
  { name: "Shaheen Air International", code: "NL", country: "Pakistan" },
  { name: "Shandong Airlines", code: "SC", country: "China" },
  { name: "Shanghai Airlines", code: "FM", country: "China" },
  { name: "Sharp Airlines", code: "SH", country: "Australia" },
  { name: "Shenzhen Airlines", code: "ZH", country: "China" },
  { name: "Shuttle America", code: "S5", country: "United States" },
  { name: "Sibaviatrans", code: "5M", country: "Russia" },
  { name: "Sichuan Airlines", code: "3U", country: "China" },
  { name: "Siem Reap Airways", code: "FT", country: "Cambodia" },
  { name: "SilkAir", code: "MI", country: "Singapore" },
  { name: "Silver Airways (3M)", code: "3M", country: "United States" },
  { name: "Skagway Air Service", code: "N5", country: "United States" },
  { name: "Sky Airline", code: "H2", country: "Chile" },
  { name: "Sky Express", code: "XW", country: "Russia" },
  { name: "Sky Regional", code: "RS", country: "Canada" },
  { name: "Sky Wing Pacific", code: "C7", country: "South Korea" },
  { name: "SkyBahamas Airlines", code: "Q7", country: "Bahamas" },
  { name: "SkyEurope", code: "NE", country: "Slovakia" },
  { name: "Skyjet Airlines", code: "UQ", country: "Uganda" },
  { name: "Skymark Airlines", code: "BC", country: "Japan" },
  { name: "Skynet Airlines", code: "SI", country: "Ireland" },
  { name: "Skynet Asia Airways", code: "6J", country: "Japan" },
  { name: "Skyservice Airlines", code: "5G", country: "Canada" },
  { name: "Skywalk Airlines", code: "AL", country: "United States" },
  { name: "Skyways Express", code: "JZ", country: "Sweden" },
  { name: "SkyWest", code: "OO", country: "United States" },
  { name: "Skywest Australia", code: "XR", country: "Australia" },
  { name: "SkyWork Airlines", code: "SX", country: "Switzerland" },
  { name: "SmartLynx Airlines", code: "6Y", country: "Latvia" },
  { name: "Snowbird Airlines", code: "S8", country: "Finland" },
  { name: "SOCHI AIR", code: "CQ", country: "Russia" },
  { name: "SOCHI AIR CHATER", code: "Q3", country: "Russia" },
  { name: "SOCHI AIR EXPRESS", code: "Q4", country: "Russia" },
  { name: "Solomon Airlines", code: "IE", country: "Solomon Islands" },
  { name: "South East Asian Airlines", code: "DG", country: "Philippines" },
  { name: "Southern Winds Airlines", code: "A4", country: "Argentina" },
  { name: "Southjet", code: "76", country: "United States" },
  { name: "Southjet cargo", code: "78", country: "United States" },
  { name: "Southjet connect", code: "77", country: "United States" },
  { name: "Spanair", code: "JK", country: "Spain" },
  { name: "Spike Airlines", code: "S0", country: "United States" },
  { name: "Spirit of Manila Airlines", code: "SM", country: "Philippines" },
  { name: "Spring Airlines", code: "9S", country: "China" },
  { name: "Spring Airlines Japan", code: "IJ", country: "Japan" },
  { name: "Sriwijaya Air", code: "SJ", country: "Indonesia" },
  { name: "Star Flyer", code: "7G", country: "Japan" },
  { name: "Star Peru (2I)", code: "2I", country: "Peru" },
  { name: "Star1 Airlines", code: "V9", country: "Lithuania" },
  { name: "Starbow Airlines", code: "S9", country: "Ghana" },
  { name: "Starline.kz", code: "DZ", country: "Kazakhstan" },
  { name: "Sterling Airlines", code: "NB", country: "Denmark" },
  { name: "STP Airways", code: "8F", country: "Sao Tome and Principe" },
  { name: "Strategic Airlines", code: "VC", country: "Australia" },
  { name: "Sudan Airways", code: "SD", country: "Sudan" },
  { name: "Sun Country Airlines", code: "SY", country: "United States" },
  { name: "Sun D'Or", code: "7L", country: "Israel" },
  { name: "SunExpress", code: "XQ", country: "Turkey" },
  { name: "Sunwing", code: "WG", country: "Canada" },
  { name: "Surinam Airways", code: "PY", country: "Suriname" },
  { name: "Svyaz Rossiya", code: "7R", country: "Russia" },
  { name: "Swe Fly", code: "WV", country: "Sweden" },
  { name: "Swissair", code: "SR", country: "Switzerland" },
  { name: "Syrian Arab Airlines", code: "RB", country: "Syrian Arab Republic" },
  { name: "T.J. Air", code: "TJ", country: "United States" },
  { name: "TAAG Angola Airlines", code: "DT", country: "Angola" },
  { name: "TACA Peru", code: "T0", country: "Peru" },
  { name: "TACV", code: "VR", country: "Portugal" },
  { name: "Tajik Air", code: "7J", country: "Tajikistan" },
  { name: "TAM Brazilian Airlines", code: "JJ", country: "Brazil" },
  { name: "TAM Mercosur", code: "PZ", country: "Paraguay" },
  { name: "TAME", code: "EQ", country: "Ecuador" },
  { name: "TAMPA", code: "QT", country: "Colombia" },
  { name: "Tarom", code: "RO", country: "Romania" },
  { name: "Tatarstan Airlines", code: "U9", country: "Russia" },
  { name: "Texas Wings", code: "TQ", country: "United States" },
  { name: "Thai Air Cargo", code: "T2", country: "Thailand" },
  { name: "Thai AirAsia", code: "FD", country: "Thailand" },
  { name: "Thai Lion Air", code: "SL", country: "Thailand" },
  { name: "Thai Smile Airways", code: "WE", country: "Thailand" },
  { name: "Thomas Cook Airlines", code: "FQ", country: "Belgium" },
  { name: "Thomsonfly", code: "BY", country: "United Kingdom" },
  { name: "Tiara Air", code: "3P", country: "Aruba" },
  { name: "Tiger Airways Australia", code: "TT", country: "Australia" },
  { name: "Tomp Airlines", code: "ZT", country: "Chile" },
  { name: "Trans Pas Air", code: "T6", country: "United States" },
  { name: "Trans States Airlines", code: "AX", country: "United States" },
  { name: "Transaero Airlines", code: "UN", country: "Russia" },
  { name: "TransAsia Airways", code: "GE", country: "Taiwan" },
  { name: "Transavia France", code: "TO", country: "France" },
  { name: "TransBrasil Airlines", code: "TH", country: "Brazil" },
  { name: "TransHolding", code: "TI", country: "Brazil" },
  { name: "TransHolding System", code: "YO", country: "Brazil" },
  { name: "TransNusa Air", code: "M8", country: "Indonesia" },
  { name: "TransRussiaAirlines", code: "1E", country: "Russia" },
  { name: "Transwest Air", code: "9T", country: "Canada" },
  { name: "TrasBrasil", code: "TB", country: "Brazil" },
  { name: "Travel Service", code: "QS", country: "Czech Republic" },
  { name: "TRIP Linhas A", code: "8R", country: "Brazil" },
  { name: "Tropic Air", code: "PM", country: "Belize" },
  { name: "TUIfly", code: "X3", country: "Germany" },
  { name: "TUIfly (X3)", code: "11", country: "Germany" },
  { name: "TUIfly Nordic", code: "6B", country: "Sweden" },
  { name: "Tuninter", code: "UG", country: "Tunisia" },
  { name: "Turan Air", code: "3T", country: "Azerbaijan" },
  { name: "Turkmenistan Airlines", code: "T5", country: "Turkmenistan" },
  { name: "Tway Airlines", code: "TW", country: "South Korea" },
  { name: "Twin Jet", code: "T7", country: "France" },
  { name: "Tyrolean Airways", code: "VO", country: "Austria" },
  { name: "Ukraine International Airlines", code: "PS", country: "Ukraine" },
  { name: "UM Airlines", code: "UF", country: "Ukraine" },
  { name: "Uni Air", code: "B7", country: "Taiwan" },
  { name: "United Airways", code: "4H", country: "Bangladesh" },
  { name: "Ural Airlines", code: "U6", country: "Russia" },
  { name: "US Airways", code: "US", country: "United States" },
  { name: "US Helicopter Corporation", code: "UH", country: "United States" },
  { name: "Usa Sky Cargo", code: "E1", country: "United States" },
  { name: "USA3000 Airlines", code: "U5", country: "United States" },
  { name: "UTair Aviation", code: "UT", country: "Russia" },
  { name: "UTair-Express", code: "UR", country: "Russia" },
  { name: "UVT Aero", code: "UW", country: "Russia" },
  { name: "V Air", code: "ZV", country: "Taiwan" },
  { name: "Valuair", code: "VF", country: "Singapore" },
  { name: "Varig Log", code: "LC", country: "Brazil" },
  { name: "VASP", code: "VP", country: "Brazil" },
  { name: "Via Conectia Airlines", code: "6V", country: "Uruguay" },
  { name: "VIA Líneas Aéreas", code: "V1", country: "Argentina" },
  { name: "VickJet", code: "KT", country: "France" },
  { name: "Viking Hellas", code: "VQ", country: "Greece" },
  { name: "VIM Airlines", code: "NN", country: "Russia" },
  { name: "VIP Ecuador", code: "V6", country: "Ecuador" },
  { name: "Virgin America", code: "VX", country: "United States" },
  { name: "Virgin Express", code: "TV", country: "Belgium" },
  { name: "Virgin Nigeria Airways", code: "VK", country: "Nigeria" },
  { name: "Virgin Pacific", code: "VH", country: "Fiji" },
  { name: "Virginwings", code: "YY", country: "Germany" },
  { name: "Vision Airlines (V2)", code: "V2", country: "United States" },
  { name: "VivaColombia", code: "5Z", country: "Colombia" },
  { name: "Vladivostok Air", code: "XF", country: "Russia" },
  { name: "VLM Airlines", code: "VG", country: "Belgium" },
  { name: "Voestar", code: "8K", country: "Brazil" },
  { name: "Volare Airlines", code: "VE", country: "Italy" },
  { name: "Volaris", code: "Y4", country: "Mexico" },
  { name: "Volga-Dnepr Airlines", code: "VI", country: "Russia" },
  { name: "VOLOTEA Airways", code: "V7", country: "Spain" },
  { name: "Volotea Costa Rica", code: "9V", country: "Costa Rica" },
  { name: "VRG Linhas Aereas", code: "RG", country: "Brazil" },
  { name: "Vuela Cuba", code: "6C", country: "Cuba" },
  { name: "Vuola Italia", code: "4S", country: "Italy" },
  { name: "Wayraper", code: "7W", country: "Peru" },
  { name: "WebJet Linhas A", code: "WJ", country: "Brazil" },
  { name: "Welcome Air", code: "2W", country: "Austria" },
  { name: "West Air China", code: "PN", country: "China" },
  { name: "West Coast Air", code: "8O", country: "Canada" },
  { name: "WestJet Encore", code: "WR", country: "Canada" },
  { name: "Widerøe", code: "WF", country: "Norway" },
  { name: "Wind Jet", code: "IV", country: "Italy" },
  { name: "Windward Islands Airways", code: "WM", country: "Netherlands Antilles" },
  { name: "Wings Air", code: "IW", country: "Indonesia" },
  { name: "Wizz Air Hungary", code: "8Z", country: "Bulgaria" },
  { name: "Wizz Air Ukraine", code: "WU", country: "Ukraine" },
  { name: "World Airways", code: "WO", country: "United States" },
  { name: "World Experience Airline", code: "W1", country: "Canada" },
  { name: "World Scale Airlines", code: "W3", country: "United States" },
  { name: "XAIR USA", code: "XA", country: "United States" },
  { name: "Xiamen Airlines", code: "MF", country: "China" },
  { name: "XL Airways France", code: "SE", country: "France" },
  { name: "Xpressair", code: "XN", country: "Indonesia" },
  { name: "XPTO", code: "XP", country: "Portugal" },
  { name: "Yamal Airlines", code: "YL", country: "Russia" },
  { name: "Yangon Airways", code: "HK", country: "Burma" },
  { name: "Yangon Airways Ltd.", code: "YH", country: "Burma" },
  { name: "Yellowstone Club Private Shuttle", code: "Y1", country: "United States" },
  { name: "Yellowtail", code: "YE", country: "United States" },
  { name: "Yemenia", code: "IY", country: "Yemen" },
  { name: "Yunnan Airlines", code: "3Q", country: "China" },
  { name: "ZABAIKAL AIRLINES", code: "Z6", country: "Russia" },
  { name: "Zabaykalskii Airlines", code: "ZP", country: "Russia" },
  { name: "Zambezi Airlines (ZMA)", code: "ZJ", country: "Zambia" },
  { name: "Zambia Skyways", code: "K8", country: "Zambia" },
  { name: "Zenith International Airline", code: "ZN", country: "Thailand" },
  { name: "Zest Air", code: "Z2", country: "Philippines" },
  { name: "Zoom Airlines", code: "Z4", country: "Canada" },
  { name: "Zz", code: "ZZ", country: "Belgium" },
];

/**
 * Instant search over airline names, IATA codes, and countries — "Qat" and
 * "QR" both find Qatar Airways, and "Nepal" lists Nepal's local carriers.
 * Name/code matches rank above country matches.
 */
export function searchAirlines(query: string, limit = 8): Airline[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const startsWith: Airline[] = [];
  const contains: Airline[] = [];
  const byCountry: Airline[] = [];

  for (const airline of AIRLINES) {
    const name = airline.name.toLowerCase();
    const code = airline.code.toLowerCase();
    const country = airline.country?.toLowerCase() ?? "";

    if (name.startsWith(q) || code === q) startsWith.push(airline);
    else if (name.includes(q)) contains.push(airline);
    else if (country.startsWith(q)) byCountry.push(airline);

    if (startsWith.length >= limit) break;
  }

  return [...startsWith, ...contains, ...byCountry].slice(0, limit);
}
